repos:
    - repo: https://github.com/psf/black
        rev: 22.1
        hooks:
          - id: black

    - repo: https://github.com/pycqa/isort
        rev: 5.10.1
        hooks:
          - id: isort

    - repo: https://github.com/pre-commit/mirrors-clang-format
        rev: v13.0.0
        hooks:
          - id: clang-format