[tool.poetry]
name = "protobuf-parser"
version = "0.1.0"
description = "Bindings for the protoc compiler"
authors = ["James <gobot1234yt@gmail.com>"]
license = "MIT"
build = "build.py"
exclude = ["protobuf_parser/protobuf/**/*"]

[tool.poetry.dependencies]
python = "^3.8"
typing-extensions = "^3.10.0"

[tool.poetry.dev-dependencies]
pybind11 = "^2.6.2"

[build-system]
requires = ["poetry-core>=1.0.0", "pybind11>=2.6.2"]
build-backend = "poetry.core.masonry.api"
